### ISSUE TITLE
ApiAuthInterceptor前置拦截器不生效

### ISSUE THREAD

**Issue by wanggja** [greatwqs/ssm2api#1]
if (handler instanceof HandlerMethod) {
            // 判断当前method上是否有标签;
            final HandlerMethod handlerMethod = (HandlerMethod) handler;
            if (handlerMethod.getMethodAnnotation(ApiAuth.class) != null) {
            	checkRequestParam(request);
            	return true;
            }
        }
handler instanceof HandlerMethod为false,方法上的注解不生效

**Comment by greatwqs** [comment]
@wanggja handler 会有多种实现, 有可能不是接口层面的请求, 如Resource(图片/CSS)
这里确定时接口的请求才进行拦截
